### ISSUE TITLE
consider using resize-observer-polyfill 

### ISSUE THREAD

**Issue by mking** [d6u/react-container-query#54]
it's quite popular (50K downloads/month) and is used in similar projects such as react-measure.

https://www.npmjs.com/package/resize-observer-polyfill

**Comment by d6u** [comment]
Thanks for your suggestion. I read the code, I think the resize-observer-lite I'm using is superior than resize-observer-polyfill because:

1. The resize-observer-lite used element-resize-detector, which is truly event based, it doesn't listen to window resize or transition end. It only triggers event when the particular element's size change.
2. In modern browser, it used a native ResizeObserver (yes, browser has support for observing resize). No need for MutationObserver.
3. None of window resize or MutationObserver will provide direct information on elements resize. The detection will waste a lot of computation.
