### ISSUE TITLE
Use react-measure?

### ISSUE THREAD

**Issue by KyleAMathews** [d6u/react-container-query#9]
Might be interesting to use https://github.com/souporserious/react-measure under the hood to detect the width changes as I'm assuming it's far more performant than checking the width many times a second with rAF.

**Comment by d6u** [comment]
This sounds like a good idea. I will first have to find a way to measure the performance then compare alternatives. Do you have any insight?

**Comment by d6u** [comment]
@KyleAMathews after some brief experiment, it doesn't seem like MutationObserver will observe elements' height and width changes other than those changes caused by set attributes on the elements. See http://codepen.io/daiweilu/pen/qZGwQB, resizing the webpage doesn't trigger any observer events. 

Do you happens to know how react-measure observer height and width changes?

**Comment by KyleAMathews** [comment]
I'm not really familiar with MutationObserver or react-measure actually... could you help out @souporserious perhaps?

**Comment by souporserious** [comment]
So sorry, just saw this. I'd definitely be willing to help out or answer any questions about React Measure. I use a window resize listener paired with a Mutation Observer to detect changes to width/height.

**Comment by souporserious** [comment]
So I did some digging last night and this morning. I don't think `react-measure` would be best for this. What about ripping out your size detection for something like this https://github.com/wnr/element-resize-detector seems pretty performant from what I can see. Here's a codepen showing it in action http://codepen.io/souporserious/pen/gMgamo/

**Comment by d6u** [comment]
@souporserious Thanks for sharing. So far I found two "polyfills" pretty attractive:
1. what you give me https://github.com/wnr/element-resize-detector
2. https://github.com/marcj/css-element-queries
There are also a React based solution https://github.com/ctrlplusb/react-sizeme to provide sizes. They are all "event" based, which should be pretty performant.
Do you happen to any recommendations among those (I figured it doesn't hurt to ask 😄 )?

**Comment by souporserious** [comment]
I actually found that one from an issue in the css element queries repo :) https://github.com/marcj/css-element-queries/issues/74

From the little research I've done. I personally like wnr's approach. Seems pretty active in development, smaller file size than react-sizeme, and you get the benefit of being able to use it outside of React for whatever reason. I'm willing to help to try and solve any performance issues. I want to start using your lib at my work :) love the idea of responsive components!

**Comment by souporserious** [comment]
Haha looks like react-sizeme uses css-element-queries https://github.com/ctrlplusb/react-sizeme#extreme-appreciation seems like you could just use css-element-queries since you just need a callback on dimension changes.

**Comment by d6u** [comment]
@souporserious Maybe you meant element-resize-detector [based on package.json](https://github.com/ctrlplusb/react-sizeme/blob/244bc9a4bae301ef4aa9cb433869d44755a0aed0/package.json#L89)?

Awesome! Now I have a path forward. Let me know any feedback when you got to use it at work 👍

**Comment by souporserious** [comment]
Yeah my bad, I just noticed react-sizeme utilizes that same library. Seems like you could you use that or element-resize-detector directly. Excited to see some perf gains!

**Comment by souporserious** [comment]
@d6u so I went a little crazy this weekend and did a bunch of research on event based element detection and rewrote react-measure to utilize [element-resize-detector](https://github.com/wnr/element-resize-detector). So now I think this library is able to utilize react-measure if you'd like it too. As a bonus I think it would solve this issue as well https://github.com/d6u/react-container-query/issues/14 since I pass down all the dimensions and positioning of the component. I can try and do a PR into your lib if you'd like, just let me know :)

**Comment by d6u** [comment]
@souporserious Thanks! I love the idea to piggyback on your research 😉  Apologies for not really working on this issue. Has been super busy recently.

Do you foresee any API changes if we depends upon react-measure. I'm less worried about the internal logic (I'm sure it will be a lot less logic 🎉 ). Specifically I like to learn more about how this is going to affect the [mixin API](https://github.com/d6u/react-container-query#createcontainerquerymixinquery-opts). To be honest I'm not sure about the value of mixin today. My impression is that mixins is very useful, but less cool/clean since there are high order component. By looking through react-measure's README briefly, I'm don't think the mixin API can exist anymore. What do we lost if we remove the mixin API?

Let me know what you need. I'd love to add you as a contributor if that makes collaboration easier for you.

**Comment by souporserious** [comment]
Unfortunately, I'm not well versed in mixins :/ from what I've seen in other libraries I've seen mixins fall away in favor of Higher Order Components. But that is up to you if you would still like to keep that, I can try and do some research to see if it would affect it or not. I'm not sure you lose anything besides the mixin API itself. You could just allow a HOC and pass down the proper props to the component. Something like `this.props.container.query` and `this.props.container.dimensions` or `this.props.containerQuery` and `this.props.containerDimensions` probably the latter since you aren't breaking anything. I don't think adding react-measure would be breaking anything besides mixins. Most of it seems like it would be under the hood and the addition of a dimensions prop passed down.

When I get a chance I'll try out PR with the update and see how hard it would be and what breaks.

**Comment by d6u** [comment]
The plan sounds good to me! And I'm fine with deprecating mixin API.

**Comment by souporserious** [comment]
@d6u do you have a contributing guide? Is there some sort of watch task or do I just need to rebuild every time I change something? Please let me know, going to try and get to it tonight :)

**Comment by d6u** [comment]
Hi @souporserious, I've added some notes here https://github.com/d6u/react-container-query/blob/master/CONTRIBUTION.md. I don't get contributors a lot. Let me know if there is anything I can improve.

**Comment by souporserious** [comment]
Awesome, that's perfect. Thanks! I'll let you know if I need anymore help.

**Comment by souporserious** [comment]
@d6u I wasn't able to get to a PR. However I have this [codepen](http://codepen.io/souporserious/pen/QEvNjj/) showing how it will work with react-measure. Seems pretty sweet! I'm currently wrapped up in other work so feel free to swap it in if you get a chance before me. I'll let you know when I can work on this again.

**Comment by d6u** [comment]
@souporserious Thanks for your demo! I finally have some time and made some progress at https://github.com/d6u/react-container-query/pull/21 (very rough).

I decided to use element-resize-detector directly so I can maintain the logic directly (no idea whether it's a good thing or not :P), but I did take many inspirations from both your CodePen demo and react-measure.

**Comment by souporserious** [comment]
Nice! Excited to see how it turns out :)

**Comment by d6u** [comment]
Hi, please check out [0.5.0 release](https://github.com/d6u/react-container-query/releases/tag/v0.5.0)! There are a few breaking changes, and I removed a lot of APIs. But it should be faster than ever 🚀 !
